name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick
      - name: Generate Pictures
        run: |
          make -C typst-report
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: typst-report/main.typ