name: Build and Generate Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install PETSc, MPI and OpenMPI
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: petsc-dev libpetsc-real-dev mpi-default-bin mpi-default-dev openmpi-bin openmpi-common libopenmpi-dev
        version: 1.0

    - name: Build
      run: |
        git submodule init
        git submodule update
        (cd deps/petsc && ./configure && make)
        make

    - name: Archive Artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: bin/main
